[[pages]]
path = "/Users/kilian/Documents/GitHub/Projet-3/STREAMLIT/pages/0 - accueil.py"
name = "Accueil"
icon = "âš½"

[[pages]]
path = "/Users/kilian/Documents/GitHub/Projet-3/STREAMLIT/pages/1 - similarite.py"
name = "Recherche d'un joueur similaire"
icon = "ğŸ‘¬ğŸ»"

[[pages]]
path = "/Users/kilian/Documents/GitHub/Projet-3/STREAMLIT/pages/2 - ideal.py"
name = "Trouver le joueur idÃ©al"
icon = "ğŸ”"
